#!/usr/bin/env bash
set -euo pipefail

APP_NAME="3xui-bw-guard"
APP_TITLE="3x-ui Bandwidth Guard"
APP_VERSION="2.0.0"
APP_DIR="/etc/${APP_NAME}"
CONF_FILE="${APP_DIR}/${APP_NAME}.conf"
STATE_DIR="/run/${APP_NAME}"
INSTALL_PATH="/usr/local/sbin/${APP_NAME}"
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"
NFT_TABLE4="${APP_NAME//-/_}_4"
NFT_TABLE6="${APP_NAME//-/_}_6"
COLOR=1

c_reset='\033[0m'; c_red='\033[31m'; c_green='\033[32m'; c_yellow='\033[33m'; c_blue='\033[34m'; c_mag='\033[35m'; c_cyan='\033[36m'; c_bold='\033[1m'; c_dim='\033[2m'
if [[ ! -t 1 ]]; then COLOR=0; fi
paint() { local color="$1"; shift; if [[ "$COLOR" -eq 1 ]]; then printf "%b%s%b\n" "$color" "$*" "$c_reset"; else printf "%s\n" "$*"; fi; }
info(){ paint "$c_cyan" "[i] $*"; }
success(){ paint "$c_green" "[+] $*"; }
warn(){ paint "$c_yellow" "[!] $*"; }
error(){ paint "$c_red" "[x] $*" >&2; }
header(){ paint "$c_bold$c_blue" "== $* =="; }
subtle(){ paint "$c_dim" "$*"; }

banner(){
  if [[ "$COLOR" -eq 1 ]]; then
    printf '%b\n' "$c_bold$c_mag"
  fi
  cat <<'EOF'
  ____        _    _       _                         _
 |___ \__  _| |  | |_   _(_)_ __ ___   __ _ _ __ __| |
   __) \ \/ / |  | | | | | | '_ ` _ \ / _` | '__/ _` |
  / __/ >  <| |__| | |_| | | | | | | | (_| | | | (_| |
 |_____/_/\_\\____/ \__,_|_|_| |_| |_|\__,_|_|  \__,_|

                3x-ui inbound bandwidth guard
EOF
  if [[ "$COLOR" -eq 1 ]]; then
    printf '%b' "$c_reset"
  fi
  subtle "Version ${APP_VERSION}"
}

need_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]] || { error "Run as root."; exit 1; }; }
cmd_exists(){ command -v "$1" >/dev/null 2>&1; }
trim(){ local s="$*"; s="${s#${s%%[![:space:]]*}}"; s="${s%${s##*[![:space:]]}}"; printf '%s' "$s"; }
is_yes(){ [[ "${1,,}" == "y" || "${1,,}" == "yes" || "${1,,}" == "1" || "${1,,}" == "true" ]]; }
ensure_dirs(){ mkdir -p "$APP_DIR" "$STATE_DIR"; }

prompt_default(){
  local question="$1" default="$2" answer=""
  if [[ -t 0 ]]; then
    if [[ -n "$default" ]]; then
      read -r -p "$question [$default]: " answer || true
    else
      read -r -p "$question: " answer || true
    fi
    answer="$(trim "$answer")"
    if [[ -z "$answer" ]]; then
      printf '%s' "$default"
    else
      printf '%s' "$answer"
    fi
  else
    printf '%s' "$default"
  fi
}

confirm(){
  local question="$1" default="${2:-y}" answer=""
  if [[ ! -t 0 ]]; then
    [[ "$default" == "y" ]]
    return
  fi
  if [[ "$default" == "y" ]]; then
    read -r -p "$question [Y/n]: " answer || true
    answer="$(trim "$answer")"
    [[ -z "$answer" ]] && return 0
    is_yes "$answer"
  else
    read -r -p "$question [y/N]: " answer || true
    answer="$(trim "$answer")"
    [[ -z "$answer" ]] && return 1
    is_yes "$answer"
  fi
}

write_default_config(){
  [[ -f "$CONF_FILE" ]] && return 0
  cat > "$CONF_FILE" <<'CFG'
# 3xui-bw-guard configuration
# Empty MANAGED_PORTS means auto-detect from XRAY_CONFIG_PATH using jq.
# Rates accept tc syntax, e.g. 256kbit, 2mbit, 25mbit, 1gbit.

IFACE="auto"
INGRESS_IFB="ifb3xui0"
XRAY_CONFIG_PATH=""
MANAGED_PORTS=""
EXCLUDE_PORTS=""
EXEMPT_IPS="127.0.0.1,::1"
LIMIT_DOWN="5mbit"
LIMIT_UP="1mbit"
UPLINK_RATE="auto"
INGRESS_RATE="auto"
MAX_CONN_PER_IP="0"
SMART_BURST="yes"
BURST_INTERVAL_MS="120"
SCAN_INTERVAL="5"
FLOW_GRACE_SECONDS="30"
LOG_LEVEL="info"
CFG
  success "Wrote default config: $CONF_FILE"
}

save_config(){
  mkdir -p "$APP_DIR"
  cat > "$CONF_FILE" <<CFG
# 3xui-bw-guard configuration
# Generated by ${APP_NAME} wizard on $(date -u +'%Y-%m-%d %H:%M:%S UTC')
# Empty MANAGED_PORTS means auto-detect from XRAY_CONFIG_PATH using jq.
# Rates accept tc syntax, e.g. 256kbit, 2mbit, 25mbit, 1gbit.

IFACE="${IFACE}"
INGRESS_IFB="${INGRESS_IFB}"
XRAY_CONFIG_PATH="${XRAY_CONFIG_PATH}"
MANAGED_PORTS="${MANAGED_PORTS}"
EXCLUDE_PORTS="${EXCLUDE_PORTS}"
EXEMPT_IPS="${EXEMPT_IPS}"
LIMIT_DOWN="${LIMIT_DOWN}"
LIMIT_UP="${LIMIT_UP}"
UPLINK_RATE="${UPLINK_RATE}"
INGRESS_RATE="${INGRESS_RATE}"
MAX_CONN_PER_IP="${MAX_CONN_PER_IP}"
SMART_BURST="${SMART_BURST}"
BURST_INTERVAL_MS="${BURST_INTERVAL_MS}"
SCAN_INTERVAL="${SCAN_INTERVAL}"
FLOW_GRACE_SECONDS="${FLOW_GRACE_SECONDS}"
LOG_LEVEL="${LOG_LEVEL}"
CFG
}

write_service(){
  cat > "$SERVICE_FILE" <<EOF2
[Unit]
Description=3x-ui inbound per-IP bandwidth guard
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_PATH} run-daemon
ExecStop=${INSTALL_PATH} stop-runtime
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF2
  systemctl daemon-reload
  success "Wrote systemd service: $SERVICE_FILE"
}

install_deps(){
  header "Installing dependencies"
  if cmd_exists apt-get; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y iproute2 nftables conntrack jq ethtool kmod
  elif cmd_exists dnf; then
    dnf install -y iproute nftables conntrack-tools jq ethtool kmod
  elif cmd_exists yum; then
    yum install -y iproute nftables conntrack-tools jq ethtool kmod
  elif cmd_exists pacman; then
    pacman -Sy --noconfirm iproute2 nftables conntrack-tools jq ethtool kmod
  elif cmd_exists zypper; then
    zypper --non-interactive install iproute2 nftables conntrack-tools jq ethtool kmod
  else
    warn "Unsupported package manager. Install manually: iproute2, nftables, conntrack-tools, jq, ethtool, kmod"
  fi
}

copy_self(){
  local src
  src="$(readlink -f "$0")"
  install -m 0755 "$src" "$INSTALL_PATH"
  success "Installed script to $INSTALL_PATH"
}

load_config(){
  [[ -f "$CONF_FILE" ]] || { error "Config not found: $CONF_FILE"; exit 1; }
  # shellcheck source=/dev/null
  source "$CONF_FILE"
  IFACE="${IFACE:-auto}"
  INGRESS_IFB="${INGRESS_IFB:-ifb3xui0}"
  XRAY_CONFIG_PATH="${XRAY_CONFIG_PATH:-}"
  MANAGED_PORTS="${MANAGED_PORTS:-}"
  EXCLUDE_PORTS="${EXCLUDE_PORTS:-}"
  EXEMPT_IPS="${EXEMPT_IPS:-}"
  LIMIT_DOWN="${LIMIT_DOWN:-0}"
  LIMIT_UP="${LIMIT_UP:-0}"
  UPLINK_RATE="${UPLINK_RATE:-auto}"
  INGRESS_RATE="${INGRESS_RATE:-auto}"
  MAX_CONN_PER_IP="${MAX_CONN_PER_IP:-0}"
  SMART_BURST="${SMART_BURST:-yes}"
  BURST_INTERVAL_MS="${BURST_INTERVAL_MS:-120}"
  SCAN_INTERVAL="${SCAN_INTERVAL:-5}"
  FLOW_GRACE_SECONDS="${FLOW_GRACE_SECONDS:-30}"
  LOG_LEVEL="${LOG_LEVEL:-info}"
}

log_debug(){ [[ "$LOG_LEVEL" == "debug" ]] && info "$*" || true; }

join_by(){ local IFS="$1"; shift; echo "$*"; }
normalize_csv(){
  local input="$1"; local out=() item
  IFS=',' read -r -a arr <<< "$input"
  for item in "${arr[@]:-}"; do
    item="$(trim "$item")"
    [[ -n "$item" ]] && out+=("$item")
  done
  join_by ',' "${out[@]:-}"
}

port_in_list(){
  local port="$1" list="$2" item
  IFS=',' read -r -a arr <<< "$list"
  for item in "${arr[@]:-}"; do
    [[ "$item" == "$port" ]] && return 0
  done
  return 1
}

is_ipv6(){ [[ "$1" == *:* ]]; }

detect_iface(){
  if [[ "$IFACE" != "auto" && -n "$IFACE" ]]; then
    printf '%s' "$IFACE"
    return 0
  fi
  local d
  d="$(ip -o route get 1.1.1.1 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit}}')"
  if [[ -z "$d" ]]; then
    d="$(ip -o route show default 2>/dev/null | awk '/default/ {for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit}}')"
  fi
  [[ -n "$d" ]] || { error "Could not auto-detect WAN interface. Set IFACE manually."; exit 1; }
  printf '%s' "$d"
}

detect_xray_config(){
  local candidates=()
  [[ -n "$XRAY_CONFIG_PATH" ]] && candidates+=("$XRAY_CONFIG_PATH")
  candidates+=(
    "/usr/local/x-ui/bin/config.json"
    "/etc/x-ui/config.json"
    "/usr/local/etc/x-ui/config.json"
    "/opt/3x-ui/bin/config.json"
  )
  local c
  for c in "${candidates[@]}"; do
    [[ -f "$c" ]] && { printf '%s' "$c"; return 0; }
  done
  return 1
}

detect_ports(){
  local ports_raw="$(normalize_csv "$MANAGED_PORTS")"
  local excludes="$(normalize_csv "$EXCLUDE_PORTS")"
  local final=() p cfg

  if [[ -z "$ports_raw" ]]; then
    if cfg="$(detect_xray_config)"; then
      ports_raw="$(jq -r '.inbounds[]? | .port? // empty' "$cfg" 2>/dev/null | awk 'NF' | sort -n | paste -sd, -)"
      log_debug "Detected Xray config: $cfg"
    fi
  fi

  [[ -n "$ports_raw" ]] || { error "No managed ports found. Set MANAGED_PORTS or XRAY_CONFIG_PATH."; exit 1; }

  IFS=',' read -r -a arr <<< "$ports_raw"
  for p in "${arr[@]}"; do
    p="$(trim "$p")"
    [[ "$p" =~ ^[0-9]+$ ]] || continue
    (( p >= 1 && p <= 65535 )) || continue
    if [[ -n "$excludes" ]] && port_in_list "$p" "$excludes"; then
      continue
    fi
    final+=("$p")
  done

  ((${#final[@]} > 0)) || { error "Managed port list is empty after exclusions."; exit 1; }
  printf '%s\n' "${final[@]}" | sort -n -u
}

rate_to_bps(){
  local rate="${1,,}"
  [[ "$rate" == "0" || "$rate" == "off" || "$rate" == "none" ]] && { echo 0; return 0; }
  if [[ "$rate" =~ ^([0-9]+)(kbit|mbit|gbit)$ ]]; then
    local n="${BASH_REMATCH[1]}" u="${BASH_REMATCH[2]}"
    case "$u" in
      kbit) echo $((n * 1000));;
      mbit) echo $((n * 1000 * 1000));;
      gbit) echo $((n * 1000 * 1000 * 1000));;
    esac
    return 0
  fi
  error "Unsupported rate format: $1"
  exit 1
}

auto_link_rate(){
  local iface="$1" speed
  if cmd_exists ethtool; then
    speed="$(ethtool "$iface" 2>/dev/null | awk -F': ' '/Speed:/ {print tolower($2)}' | head -n1)"
    if [[ "$speed" =~ ^([0-9]+)mb/s$ ]]; then
      echo "${BASH_REMATCH[1]}mbit"
      return 0
    elif [[ "$speed" =~ ^([0-9]+)gb/s$ ]]; then
      echo "${BASH_REMATCH[1]}gbit"
      return 0
    fi
  fi
  if [[ -r "/sys/class/net/${iface}/speed" ]]; then
    speed="$(cat "/sys/class/net/${iface}/speed" 2>/dev/null || true)"
    if [[ "$speed" =~ ^[0-9]+$ && "$speed" -gt 0 ]]; then
      echo "${speed}mbit"
      return 0
    fi
  fi
  echo "1gbit"
}

compute_burst(){
  local rate="$1" interval_ms="$2"
  [[ "${SMART_BURST,,}" == "yes" ]] || { echo "64kb"; return 0; }
  local bps bytes mtu=1500 min max
  bps="$(rate_to_bps "$rate")"
  (( bps > 0 )) || { echo "16kb"; return 0; }
  bytes=$(( (bps * interval_ms) / 8000 ))
  min=$(( mtu * 20 ))
  max=$(( 4 * 1024 * 1024 ))
  (( bytes < min )) && bytes=$min
  (( bytes > max )) && bytes=$max
  echo "${bytes}b"
}

hash_minor(){
  local s="$1" sum
  sum="$(printf '%s' "$s" | cksum | awk '{print $1}')"
  echo $(( (sum % 60000) + 1000 ))
}

hash_handle(){
  local s="$1" sum
  sum="$(printf '%s' "$s" | cksum | awk '{print $1}')"
  printf '0x%x' "$(( (sum % 0x7fffffff) + 1 ))"
}

setup_modules(){
  modprobe ifb >/dev/null 2>&1 || true
  modprobe sch_htb >/dev/null 2>&1 || true
  modprobe sch_fq_codel >/dev/null 2>&1 || true
  modprobe cls_flower >/dev/null 2>&1 || true
  modprobe act_mirred >/dev/null 2>&1 || true
}

resolve_rates(){
  EFFECTIVE_IFACE="$(detect_iface)"
  EFFECTIVE_UPLINK_RATE="$UPLINK_RATE"
  EFFECTIVE_INGRESS_RATE="$INGRESS_RATE"
  [[ "${EFFECTIVE_UPLINK_RATE,,}" == "auto" ]] && EFFECTIVE_UPLINK_RATE="$(auto_link_rate "$EFFECTIVE_IFACE")"
  [[ "${EFFECTIVE_INGRESS_RATE,,}" == "auto" ]] && EFFECTIVE_INGRESS_RATE="$EFFECTIVE_UPLINK_RATE"
  DOWN_BURST="$(compute_burst "$LIMIT_DOWN" "$BURST_INTERVAL_MS")"
  UP_BURST="$(compute_burst "$LIMIT_UP" "$BURST_INTERVAL_MS")"
  ROOT_E_BURST="$(compute_burst "$EFFECTIVE_UPLINK_RATE" "$BURST_INTERVAL_MS")"
  ROOT_I_BURST="$(compute_burst "$EFFECTIVE_INGRESS_RATE" "$BURST_INTERVAL_MS")"
}

setup_qdisc(){
  setup_modules
  local iface="$EFFECTIVE_IFACE" ifb="$INGRESS_IFB"
  ip link show "$ifb" >/dev/null 2>&1 || ip link add "$ifb" type ifb
  ip link set dev "$ifb" up

  tc qdisc replace dev "$iface" root handle 1: htb default 999
  tc class replace dev "$iface" parent 1: classid 1:1 htb rate "$EFFECTIVE_UPLINK_RATE" ceil "$EFFECTIVE_UPLINK_RATE" burst "$ROOT_E_BURST" cburst "$ROOT_E_BURST"
  tc class replace dev "$iface" parent 1:1 classid 1:999 htb rate "$EFFECTIVE_UPLINK_RATE" ceil "$EFFECTIVE_UPLINK_RATE" burst "$ROOT_E_BURST" cburst "$ROOT_E_BURST" prio 7
  tc qdisc replace dev "$iface" parent 1:999 fq_codel

  tc qdisc replace dev "$iface" handle ffff: ingress
  tc filter replace dev "$iface" parent ffff: protocol all matchall action mirred egress redirect dev "$ifb"

  tc qdisc replace dev "$ifb" root handle 2: htb default 999
  tc class replace dev "$ifb" parent 2: classid 2:1 htb rate "$EFFECTIVE_INGRESS_RATE" ceil "$EFFECTIVE_INGRESS_RATE" burst "$ROOT_I_BURST" cburst "$ROOT_I_BURST"
  tc class replace dev "$ifb" parent 2:1 classid 2:999 htb rate "$EFFECTIVE_INGRESS_RATE" ceil "$EFFECTIVE_INGRESS_RATE" burst "$ROOT_I_BURST" cburst "$ROOT_I_BURST" prio 7
  tc qdisc replace dev "$ifb" parent 2:999 fq_codel
}

cleanup_qdisc(){
  local iface ifb
  iface="$(detect_iface 2>/dev/null || true)"
  ifb="${INGRESS_IFB:-ifb3xui0}"
  [[ -n "$iface" ]] && tc qdisc del dev "$iface" root 2>/dev/null || true
  [[ -n "$iface" ]] && tc qdisc del dev "$iface" ingress 2>/dev/null || true
  ip link show "$ifb" >/dev/null 2>&1 && tc qdisc del dev "$ifb" root 2>/dev/null || true
  ip link show "$ifb" >/dev/null 2>&1 && ip link set dev "$ifb" down 2>/dev/null || true
  ip link show "$ifb" >/dev/null 2>&1 && ip link delete "$ifb" type ifb 2>/dev/null || true
}

cleanup_nft(){
  nft delete table ip "$NFT_TABLE4" 2>/dev/null || true
  nft delete table ip6 "$NFT_TABLE6" 2>/dev/null || true
}

build_nft(){
  cleanup_nft
  (( MAX_CONN_PER_IP > 0 )) || return 0

  local ports_csv exempts_csv v4set="" v6set="" item
  ports_csv="$(printf '%s, ' "${PORTS[@]}" | sed 's/, $//')"
  exempts_csv="$(normalize_csv "$EXEMPT_IPS")"

  if [[ -n "$exempts_csv" ]]; then
    local v4=() v6=()
    IFS=',' read -r -a exarr <<< "$exempts_csv"
    for item in "${exarr[@]}"; do
      item="$(trim "$item")"
      [[ -z "$item" ]] && continue
      if is_ipv6 "$item"; then v6+=("$item"); else v4+=("$item"); fi
    done
    if ((${#v4[@]} > 0)); then v4set="$(printf '%s, ' "${v4[@]}" | sed 's/, $//')"; fi
    if ((${#v6[@]} > 0)); then v6set="$(printf '%s, ' "${v6[@]}" | sed 's/, $//')"; fi
  fi

  {
    echo "table ip ${NFT_TABLE4} {"
    echo "  set connlimit_src { type ipv4_addr; flags dynamic; size 65535; }"
    echo "  chain input { type filter hook input priority -5; policy accept; jump connlimit; }"
    echo "  chain connlimit {"
    [[ -n "$v4set" ]] && echo "    ip saddr { ${v4set} } return"
    echo "    ct state new tcp dport { ${ports_csv} } add @connlimit_src { ip saddr ct count over ${MAX_CONN_PER_IP} } counter drop"
    echo "    ct state new udp dport { ${ports_csv} } add @connlimit_src { ip saddr ct count over ${MAX_CONN_PER_IP} } counter drop"
    echo "    return"
    echo "  }"
    echo "}"
    echo "table ip6 ${NFT_TABLE6} {"
    echo "  set connlimit_src { type ipv6_addr; flags dynamic; size 65535; }"
    echo "  chain input { type filter hook input priority -5; policy accept; jump connlimit; }"
    echo "  chain connlimit {"
    [[ -n "$v6set" ]] && echo "    ip6 saddr { ${v6set} } return"
    echo "    ct state new tcp dport { ${ports_csv} } add @connlimit_src { ip6 saddr ct count over ${MAX_CONN_PER_IP} } counter drop"
    echo "    ct state new udp dport { ${ports_csv} } add @connlimit_src { ip6 saddr ct count over ${MAX_CONN_PER_IP} } counter drop"
    echo "    return"
    echo "  }"
    echo "}"
  } | nft -f -
}

client_is_exempt(){
  local ip="$1" item list
  list="$(normalize_csv "$EXEMPT_IPS")"
  [[ -z "$list" ]] && return 1
  IFS=',' read -r -a arr <<< "$list"
  for item in "${arr[@]}"; do
    [[ "$ip" == "$item" ]] && return 0
  done
  return 1
}

ensure_port_array(){
  mapfile -t PORTS < <(detect_ports)
  PORTS_CSV="$(printf '%s,' "${PORTS[@]}" | sed 's/,$//')"
}

scan_clients_family(){
  local family="$1"
  local ct_out pmap awk_prog
  pmap="$PORTS_CSV"
  if ! ct_out="$(conntrack -L -f "$family" 2>/dev/null || true)"; then
    return 0
  fi
  awk_prog='BEGIN{split(ports,a,","); for(i in a) want[a[i]]=1}
  {
    d=""; s="";
    for(i=1;i<=NF;i++){
      if(s=="" && $i ~ /^src=/){ s=substr($i,5) }
      if(d=="" && $i ~ /^dport=/){ d=substr($i,7) }
    }
    if(s != "" && d in want) print s
  }'
  awk -v ports="$pmap" "$awk_prog" <<< "$ct_out" | sort -u
}

add_client_filters(){
  local ip="$1" family proto port minor handle
  minor="$(hash_minor "$ip")"

  if [[ "$LIMIT_DOWN" != "0" && "$LIMIT_DOWN" != "off" && "$LIMIT_DOWN" != "none" ]]; then
    tc class replace dev "$EFFECTIVE_IFACE" parent 1:1 classid "1:${minor}" htb rate "$LIMIT_DOWN" ceil "$LIMIT_DOWN" burst "$DOWN_BURST" cburst "$DOWN_BURST"
    tc qdisc replace dev "$EFFECTIVE_IFACE" parent "1:${minor}" fq_codel
  fi
  if [[ "$LIMIT_UP" != "0" && "$LIMIT_UP" != "off" && "$LIMIT_UP" != "none" ]]; then
    tc class replace dev "$INGRESS_IFB" parent 2:1 classid "2:${minor}" htb rate "$LIMIT_UP" ceil "$LIMIT_UP" burst "$UP_BURST" cburst "$UP_BURST"
    tc qdisc replace dev "$INGRESS_IFB" parent "2:${minor}" fq_codel
  fi

  if is_ipv6 "$ip"; then family="ipv6"; else family="ip"; fi

  for port in "${PORTS[@]}"; do
    for proto in tcp udp; do
      if [[ "$LIMIT_DOWN" != "0" && "$LIMIT_DOWN" != "off" && "$LIMIT_DOWN" != "none" ]]; then
        handle="$(hash_handle "egress|$family|$proto|$port|$ip")"
        tc filter replace dev "$EFFECTIVE_IFACE" parent 1: protocol "$family" pref 100 handle "$handle" flower \
          dst_ip "$ip" ip_proto "$proto" src_port "$port" classid "1:${minor}" >/dev/null
      fi
      if [[ "$LIMIT_UP" != "0" && "$LIMIT_UP" != "off" && "$LIMIT_UP" != "none" ]]; then
        handle="$(hash_handle "ingress|$family|$proto|$port|$ip")"
        tc filter replace dev "$INGRESS_IFB" parent 2: protocol "$family" pref 100 handle "$handle" flower \
          src_ip "$ip" ip_proto "$proto" dst_port "$port" classid "2:${minor}" >/dev/null
      fi
    done
  done
}

remove_client_filters(){
  local ip="$1" family proto port minor handle
  minor="$(hash_minor "$ip")"
  if is_ipv6 "$ip"; then family="ipv6"; else family="ip"; fi

  for port in "${PORTS[@]}"; do
    for proto in tcp udp; do
      handle="$(hash_handle "egress|$family|$proto|$port|$ip")"
      tc filter del dev "$EFFECTIVE_IFACE" parent 1: protocol "$family" pref 100 handle "$handle" flower 2>/dev/null || true
      handle="$(hash_handle "ingress|$family|$proto|$port|$ip")"
      tc filter del dev "$INGRESS_IFB" parent 2: protocol "$family" pref 100 handle "$handle" flower 2>/dev/null || true
    done
  done
  tc qdisc del dev "$EFFECTIVE_IFACE" parent "1:${minor}" 2>/dev/null || true
  tc qdisc del dev "$INGRESS_IFB" parent "2:${minor}" 2>/dev/null || true
  tc class del dev "$EFFECTIVE_IFACE" classid "1:${minor}" 2>/dev/null || true
  tc class del dev "$INGRESS_IFB" classid "2:${minor}" 2>/dev/null || true
}

persist_state(){
  : > "$STATE_DIR/clients.db"
  local ip
  for ip in "${!CLIENT_LAST_SEEN[@]}"; do
    printf '%s %s\n' "$ip" "${CLIENT_LAST_SEEN[$ip]}" >> "$STATE_DIR/clients.db"
  done
}

load_state(){
  declare -gA CLIENT_LAST_SEEN=()
  if [[ -f "$STATE_DIR/clients.db" ]]; then
    while read -r ip ts; do
      [[ -n "$ip" && -n "$ts" ]] && CLIENT_LAST_SEEN["$ip"]="$ts"
    done < "$STATE_DIR/clients.db"
  fi
}

reconcile_once(){
  local now ip
  now="$(date +%s)"
  declare -A seen_now=()

  while read -r ip; do
    [[ -z "$ip" ]] && continue
    client_is_exempt "$ip" && continue
    seen_now["$ip"]=1
    if [[ -z "${CLIENT_LAST_SEEN[$ip]:-}" ]]; then
      add_client_filters "$ip"
      info "attached client $ip"
    fi
    CLIENT_LAST_SEEN["$ip"]="$now"
  done < <(
    { scan_clients_family ipv4; scan_clients_family ipv6; } | sort -u
  )

  for ip in "${!CLIENT_LAST_SEEN[@]}"; do
    if [[ -z "${seen_now[$ip]:-}" ]]; then
      if (( now - CLIENT_LAST_SEEN[$ip] >= FLOW_GRACE_SECONDS )); then
        remove_client_filters "$ip"
        unset 'CLIENT_LAST_SEEN[$ip]'
        info "detached client $ip"
      fi
    fi
  done

  persist_state
}

run_daemon(){
  need_root
  ensure_dirs
  load_config
  resolve_rates
  ensure_port_array
  load_state
  setup_qdisc
  build_nft
  banner
  header "${APP_TITLE} started"
  info "Interface        : $EFFECTIVE_IFACE"
  info "Inbound ports    : $PORTS_CSV"
  info "Limit down       : $LIMIT_DOWN"
  info "Limit up         : $LIMIT_UP"
  info "Uplink rate      : $EFFECTIVE_UPLINK_RATE"
  info "Ingress rate     : $EFFECTIVE_INGRESS_RATE"
  info "Max conn / IP    : $MAX_CONN_PER_IP"
  trap 'stop_runtime; exit 0' INT TERM
  while true; do
    reconcile_once
    sleep "$SCAN_INTERVAL"
  done
}

stop_runtime(){
  load_config 2>/dev/null || true
  cleanup_nft
  cleanup_qdisc
  rm -f "$STATE_DIR/clients.db"
  success "Runtime cleaned up"
}

configtest(){
  need_root
  ensure_dirs
  load_config
  resolve_rates
  ensure_port_array
  banner
  header "Configuration test"
  printf '%-20s %s\n' "Interface" "$EFFECTIVE_IFACE"
  printf '%-20s %s\n' "Inbound ports" "$PORTS_CSV"
  printf '%-20s %s\n' "Limit down" "$LIMIT_DOWN"
  printf '%-20s %s\n' "Limit up" "$LIMIT_UP"
  printf '%-20s %s\n' "Uplink rate" "$EFFECTIVE_UPLINK_RATE"
  printf '%-20s %s\n' "Ingress rate" "$EFFECTIVE_INGRESS_RATE"
  printf '%-20s %s\n' "Down burst" "$DOWN_BURST"
  printf '%-20s %s\n' "Up burst" "$UP_BURST"
  printf '%-20s %s\n' "Max conn / IP" "$MAX_CONN_PER_IP"
  printf '%-20s %s\n' "Exempt IPs" "${EXEMPT_IPS:-<none>}"
}

show_config(){
  load_config
  banner
  header "Current configuration"
  sed -n '1,200p' "$CONF_FILE"
}

show_status(){
  load_config || true
  banner
  header "Service status"
  systemctl --no-pager --full status "$APP_NAME" || true
  echo
  header "Shaping classes (egress)"
  iface="$(detect_iface 2>/dev/null || true)"
  [[ -n "$iface" ]] && tc -s class show dev "$iface" 2>/dev/null || true
  echo
  header "Shaping classes (ingress/ifb)"
  [[ -n "${INGRESS_IFB:-}" ]] && tc -s class show dev "${INGRESS_IFB:-ifb3xui0}" 2>/dev/null || true
}

doctor(){
  banner
  header "Environment checks"
  local missing=0 c
  for c in ip tc nft conntrack jq ethtool modprobe systemctl; do
    if cmd_exists "$c"; then
      success "found: $c"
    else
      warn "missing: $c"
      missing=1
    fi
  done
  if [[ -f "$CONF_FILE" ]]; then
    success "config present: $CONF_FILE"
    load_config || true
    info "configured interface: ${IFACE:-auto}"
    info "configured xray path : ${XRAY_CONFIG_PATH:-<empty>}"
  else
    warn "config missing: $CONF_FILE"
  fi
  if cmd_exists modprobe; then
    for m in ifb sch_htb sch_fq_codel cls_flower act_mirred; do
      if modprobe -n "$m" >/dev/null 2>&1; then
        success "module ok: $m"
      else
        warn "module may be unavailable: $m"
      fi
    done
  fi
  if [[ "$missing" -eq 0 ]]; then
    success "Environment looks ready."
  else
    warn "Some required commands are missing."
  fi
}

wizard(){
  need_root
  banner
  header "Interactive setup wizard"
  mkdir -p "$APP_DIR"
  if [[ -f "$CONF_FILE" ]]; then
    load_config || true
    info "Loaded existing config: $CONF_FILE"
  else
    IFACE="auto"
    INGRESS_IFB="ifb3xui0"
    XRAY_CONFIG_PATH=""
    MANAGED_PORTS=""
    EXCLUDE_PORTS=""
    EXEMPT_IPS="127.0.0.1,::1"
    LIMIT_DOWN="5mbit"
    LIMIT_UP="1mbit"
    UPLINK_RATE="auto"
    INGRESS_RATE="auto"
    MAX_CONN_PER_IP="0"
    SMART_BURST="yes"
    BURST_INTERVAL_MS="120"
    SCAN_INTERVAL="5"
    FLOW_GRACE_SECONDS="30"
    LOG_LEVEL="info"
  fi

  IFACE="$(prompt_default 'Network interface (or auto)' "${IFACE:-auto}")"
  INGRESS_IFB="$(prompt_default 'IFB interface name' "${INGRESS_IFB:-ifb3xui0}")"
  XRAY_CONFIG_PATH="$(prompt_default '3x-ui/Xray config.json path (blank for auto-discovery)' "${XRAY_CONFIG_PATH:-}")"
  MANAGED_PORTS="$(prompt_default 'Managed inbound ports CSV (blank to auto-detect)' "${MANAGED_PORTS:-}")"
  EXCLUDE_PORTS="$(prompt_default 'Excluded ports CSV' "${EXCLUDE_PORTS:-}")"
  EXEMPT_IPS="$(prompt_default 'Exempt IPs CSV' "${EXEMPT_IPS:-127.0.0.1,::1}")"
  LIMIT_DOWN="$(prompt_default 'Per-client download limit' "${LIMIT_DOWN:-5mbit}")"
  LIMIT_UP="$(prompt_default 'Per-client upload limit' "${LIMIT_UP:-1mbit}")"
  UPLINK_RATE="$(prompt_default 'Real uplink capacity' "${UPLINK_RATE:-auto}")"
  INGRESS_RATE="$(prompt_default 'Real ingress capacity' "${INGRESS_RATE:-auto}")"
  MAX_CONN_PER_IP="$(prompt_default 'Max connections per IP (0 disables)' "${MAX_CONN_PER_IP:-0}")"
  SMART_BURST="$(prompt_default 'Smart burst (yes/no)' "${SMART_BURST:-yes}")"
  BURST_INTERVAL_MS="$(prompt_default 'Burst interval in milliseconds' "${BURST_INTERVAL_MS:-120}")"
  SCAN_INTERVAL="$(prompt_default 'Scan interval in seconds' "${SCAN_INTERVAL:-5}")"
  FLOW_GRACE_SECONDS="$(prompt_default 'Flow grace seconds' "${FLOW_GRACE_SECONDS:-30}")"
  LOG_LEVEL="$(prompt_default 'Log level (info/debug)' "${LOG_LEVEL:-info}")"

  save_config
  success "Configuration saved to $CONF_FILE"
  if confirm 'Run config test now?' y; then
    configtest || true
  fi
  if confirm 'Enable and start the service now?' y; then
    systemctl enable --now "$APP_NAME"
    success "Service enabled and started"
  fi
}

install_all(){
  need_root
  banner
  install_deps
  ensure_dirs
  copy_self
  write_default_config
  write_service
  success "Install complete."
  info "Config file : $CONF_FILE"
  info "Service     : $SERVICE_FILE"
  info "Binary      : $INSTALL_PATH"
  if [[ -t 0 ]] && confirm 'Launch setup wizard now?' y; then
    "$INSTALL_PATH" wizard
  else
    info "Next step: edit $CONF_FILE or run $INSTALL_PATH wizard"
  fi
}

uninstall_all(){
  need_root
  systemctl disable --now "$APP_NAME" 2>/dev/null || true
  cleanup_nft
  cleanup_qdisc
  rm -f "$SERVICE_FILE" "$INSTALL_PATH"
  rm -rf "$APP_DIR" "$STATE_DIR"
  systemctl daemon-reload
  success "Uninstalled $APP_NAME"
}

show_help(){
  banner
  cat <<USAGE
Usage: $0 <command>

Commands:
  install       Install dependencies, binary, config, and service
  uninstall     Remove service, config, runtime, and installed binary
  wizard        Interactive configuration wizard
  doctor        Check commands, modules, and config presence
  config        Show current configuration file
  configtest    Validate current configuration and detected ports
  apply         Apply base runtime config immediately
  enable        Enable systemd service
  disable       Disable systemd service
  start         Start systemd service
  stop          Stop systemd service
  restart       Restart systemd service
  status        Show service and tc class status
  run-daemon    Internal service entrypoint
  stop-runtime  Internal cleanup entrypoint
  version       Show script version
  help          Show this help
USAGE
}

case "${1:-help}" in
  install) install_all ;;
  uninstall) uninstall_all ;;
  wizard) wizard ;;
  doctor) doctor ;;
  config) show_config ;;
  enable) systemctl enable "$APP_NAME" ;;
  disable) systemctl disable "$APP_NAME" ;;
  start) systemctl start "$APP_NAME" ;;
  stop) systemctl stop "$APP_NAME" ;;
  restart) systemctl restart "$APP_NAME" ;;
  status) show_status ;;
  configtest) configtest ;;
  apply) need_root; load_config; resolve_rates; ensure_port_array; setup_qdisc; build_nft; success "Applied base runtime config. Restart service to fully reconcile clients." ;;
  run-daemon) run_daemon ;;
  stop-runtime) stop_runtime ;;
  version) printf '%s\n' "$APP_VERSION" ;;
  help|-h|--help) show_help ;;
  *) error "Unknown command: ${1}"; show_help; exit 1 ;;
esac
